export const jobSummarySelect = {
  id: true,
  jobNumber: true,
  title: true,
  description: true,
  customer: true,
  siteName: true,
  date: true,
  status: true,
  billingTotal: true,
  notes: true,
  customerSummary: true,
  createdAt: true,
  latestActivityAt: true,
  createdByName: true,
  invoiceNumber: true,
  invoiceDate: true,
  technician: { select: { id: true, name: true } },
  parts: {
    select: {
      id: true,
      itemId: true,
      quantity: true,
      unitCost: true,
      markupPercent: true,
      unitSell: true,
      notes: true,
      itemNameSnapshot: true,
      itemPartNumberSnapshot: true,
      createdAt: true,
      lastActivityAt: true,
      item: {
        select: {
          id: true,
          name: true,
          partNumber: true,
          unitOfMeasure: true,
          quantityOnHand: true,
          lowStockRedThreshold: true,
        },
      },
    },
  },
  _count: { select: { parts: true } },
} as const;

export const jobDetailSelect = {
  ...jobSummarySelect,
  completedAt: true,
  completedByName: true,
  invoicedByName: true,
  technicianId: true,
  history: {
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      actionType: true,
      actionLabel: true,
      details: true,
      actorName: true,
      createdAt: true,
    },
  },
} as const;