ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "email" TEXT;

ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;

ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "pinHash" TEXT NOT NULL DEFAULT '';

ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "resetToken" TEXT;

ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "resetTokenExpiry" TIMESTAMP(3);

ALTER TABLE "AppUser"
ALTER COLUMN "email" DROP NOT NULL;

ALTER TABLE "AppUser"
ALTER COLUMN "passwordHash" DROP NOT NULL;

ALTER TABLE "AppUser"
ALTER COLUMN "pinHash" SET DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS "AppUser_email_key" ON "AppUser"("email");