ALTER TABLE "AppUser"
ADD COLUMN IF NOT EXISTS "resetTokenExpiry" TIMESTAMP(3);

ALTER TABLE "AppUser"
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "passwordHash" DROP NOT NULL,
ALTER COLUMN "passwordHash" DROP DEFAULT;

DROP INDEX IF EXISTS "AppUser_name_key";